[General]
comment_delay = 35
# URL of the Instagram post to comment on
post_url = https://www.instagram.com/p/your_post_id_here/
users_per_comment = 2
custom_messages = Vamos por ese premio!, 🔥🔥🔥, Con todo! 🎉
