#CODIGO PARA OBTENER LISTA DE USERNAMES Y NOMBRES DE IG
"""// Selecciona todos los span con el atributo data-bloks-name="bk.components.Text"
var spans = document.querySelectorAll('span[data-bloks-name="bk.components.Text"]');

// Crea una lista para almacenar los nombres de usuario
var usernames = [];

// Itera sobre los span seleccionados y extrae el texto
spans.forEach(span => {
    usernames.push(span.textContent.trim());
});

// Muestra la lista de nombres de usuario en la consola
console.log(usernames);
"""



lista =[
    "lschultzb",
    "Lucas Schultz Buzeta",
    "fwdecarcer",
    "Fernando de Carcer",
    "cristobal_merino",
    "Cristóbal Merino",
    "sdonoso22",
    "Samuel Donoso",
    "valentinleiva.exe",
    "Valentín Leiva C.",
    "ro__albornoz",
    "Ro Albornoz C",
    "diegotorresca_",
    "Diego",
    "manuel_oddo_",
    "Manuel oddo",
    "laura_youlton",
    "Laura Youlton",
    "clementealdayv",
    "Clemente Alday Vidal ®️",
    "lukaohaco",
    "Luka Ohaco",
    "borjajuegos9",
    "Borja Manterola",
    "aliciagarciadelahuerta",
    "Alicia García de la Huerta R.",
    "p.santacruz.m",
    "Patricio Santa Cruz Martínez",
    "lorenzomunoozz",
    "Lorenzo.",
    "vmartinezg_",
    "Vicente Martínez",
    "coniperez1",
    "Coni Pérez",
    "pedro_alcalde",
    "Pedro Alcalde Justiniano",
    "b_langlois_b",
    "Benjamín Langlois Buchholtz",
    "cfuenzalida.i",
    "Cristóbal Fuenzalida",
    "jp_cofre",
    "Juan Pablo Cofré Celis",
    "fenozo_",
    "Feña Garrido",
    "philip_metzker",
    "philip metzker baeza",
    "r_correap",
    "Rodrigo Correa",
    "cristobal_goycoolea",
    "Cristóbal Goycoolea",
    "lucia.martinez.vial",
    "Lucha",
    "aherrerabugge",
    "Andrés Herrera Bugge",
    "__raul.sanchez__",
    "Raul Sanchez",
    "pacita.benavente",
    "Pacita Benavente Ariztía ★",
    "trinidadriobo",
    "Trinidad Riobó Maturana",
    "adelsolarr_14",
    "Agustín del Solar",
    "m.achurra",
    "Manuel Achurra",
    "luzma_bozzo",
    "Luz María ;)",
    "cristobalveas_",
    "Cristóbal Veas",
    "pedroclarkf1",
    "Pedrinski",
    "jose.friasi",
    "jose.friasi",
    "leon_montess",
    "León",
    "isi.diazarrate",
    "Titiッ",
    "jacivaldes",
    "Jacinta :)",
    "memo_crasemann",
    "Emilio Crasemann Sommer",
    "josefinamercado02",
    "Jose",
    "isidorasanchezl",
    "Isidora Sánchez Lamoliatte",
    "tvidelaa__",
    "Tomas Videla",
    "__antoniorojas",
    "Antonio José Rojas",
    "franco_coluchio",
    "Franco Coluchio",
    "maca_bennett",
    "Macarena Bennett",
    "_isavm",
    "Isabel Valenzuela Mac-Kellar",
    "_damianmaturana_",
    "Damián",
    "josemanuelpobletem",
    "José Manuel Poblete",
    "agumartinezd",
    "agustina",
    "isicruzf_",
    "Isi Cruz",
    "bunsterjc2002",
    "José Bunster",
    "_matiasrl",
    "Matías",
    "pato_cardenase",
    "pato_cardenase",
    "amelia.decarcer",
    "Amelia",
    "horacio__schmidt",
    "Horacio Schmidt Somarriva",
    "angie_azegers",
    "josefalecanda",
    "jesu.osorip",
    "J e s u",
    "a__morenomariani",
    "Andrés",
    "roberto_miguieles",
    "Roberto",
    "rociocuevaschellet",
    "Rocío",
    "ignaciaossesal",
    "Ignacia Osses Alvarado",
    "diegoedwards_consi",
    "Diego Edwards Consigliere",
    "isabelcilveti_",
    "Chicki cilveti",
    "eloyboy_",
    "Diego De La Riva Valdes",
    "martin_galdos",
    "Martin Galdos",
    "rodrigo_violic",
    "Rodrigo Violic E.  🇨🇱🇭🇷",
    "sofiaavilesp",
    "Sofía🐆",
    "_vpuigl",
    "Vicente Puig L.",
    "jarabe29",
    "Javiera Jesús Hadad",
    "joseignaciodetoro",
    "joseignaciodetoro",
    "inakiverdugoj_",
    "iñaki verdugo",
    "matias_concha_",
    "Matias Concha",
    "felipe_cortezs",
    "Felipe Cortez Suazo",
    "ratonpeludo",
    "Margarita Bernales Donoso",
    "jose.santander17",
    "José Manuel Santander",
    "elisabordagorry",
    "Elisa Bordagorry Leal",
    "eduardo_cortezs",
    "Eduardo Cortez",
    "dthmsnp",
    "Diego Thomson Padilla",
    "colleman.cl",
    "Benjamin Coll",
    "antoniarojasu",
    "Antonia Rojas",
    "_inaki_12",
    "_inaki_12",
    "pablo_gutierrez.f",
    "Pablo Gutierrez",
    "s_.yapur",
    "Cris",
    "andrescoloma.yf",
    "Andrés Coloma",
    "agu_marshall",
    "agu <3",
    "domingobolelli",
    "Domingo 🌎",
    "vicholopezre",
    "Vicente López",
    "nicogalvez1",
    "Nicolas",
    "emilio_espinoza",
    "Emilio Espinoza"]
    